on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  release:
    if: |-
      startsWith(github.event.head_commit.message, 'release') || 
      startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2

      - name: Download dependencies
        run: bun install

      - name: Build for linux-x64 and linux-arm64
        run: |
          bun build --compile --target=bun-linux-x64 ./index.ts --outfile ./ntfy-node-x64
          bun build --compile --target=bun-linux-arm64 ./index.ts --outfile ./ntfy-node-arm64

      - name: Create Release Tag
        run: |
          echo "VERSION=${GITHUB_SHA:0:8}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: |
            ntfy-node-x64
            ntfy-node-arm64