on:
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: |-
      startsWith(github.event.head_commit.message, 'release') || 
      startsWith(github.event.head_commit.message, 'Release')
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2

      - name: Download dependencies
        run: bun install

      - name: Build for linux-x64 and linux-arm64
        run: |
          bun build --compile --target=bun-linux-x64 ./index.ts --outfile ./ntfy-node-x64
          bun build --compile --target=bun-linux-arm64 ./index.ts --outfile ./ntfy-node-arm64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ntfy-node-x64
            ntfy-node-arm64
